const SECTORS = [
  {sector_code:"WATER", sector_name:"Water Supply",    sector_icon:"💧",total_projects:8, avg_physical_pct:62,financial_utilisation_pct:54,delayed_count:2,dc_flag_count:3,total_sanctioned_lakhs:145200},
  {sector_code:"SEW",   sector_name:"Sewerage & STP",  sector_icon:"🏗",total_projects:7, avg_physical_pct:41,financial_utilisation_pct:38,delayed_count:3,dc_flag_count:5,total_sanctioned_lakhs:118600},
  {sector_code:"DRAIN", sector_name:"Storm Drainage",  sector_icon:"🌧",total_projects:7, avg_physical_pct:55,financial_utilisation_pct:47,delayed_count:2,dc_flag_count:2,total_sanctioned_lakhs:62100},
  {sector_code:"SWM",   sector_name:"Solid Waste",     sector_icon:"♻",total_projects:6, avg_physical_pct:78,financial_utilisation_pct:71,delayed_count:1,dc_flag_count:0,total_sanctioned_lakhs:39800},
  {sector_code:"TRAN",  sector_name:"Urban Transport", sector_icon:"🚌",total_projects:7, avg_physical_pct:33,financial_utilisation_pct:29,delayed_count:4,dc_flag_count:4,total_sanctioned_lakhs:96400},
  {sector_code:"HOUSE", sector_name:"Housing",         sector_icon:"🏘",total_projects:8, avg_physical_pct:69,financial_utilisation_pct:63,delayed_count:2,dc_flag_count:1,total_sanctioned_lakhs:132700},
  {sector_code:"RIVER", sector_name:"Riverfront",      sector_icon:"🌊",total_projects:6, avg_physical_pct:22,financial_utilisation_pct:18,delayed_count:3,dc_flag_count:2,total_sanctioned_lakhs:48200},
  {sector_code:"LIGHT", sector_name:"Street Lighting", sector_icon:"💡",total_projects:6, avg_physical_pct:84,financial_utilisation_pct:79,delayed_count:0,dc_flag_count:0,total_sanctioned_lakhs:18400},
  {sector_code:"MARKET",sector_name:"Markets",         sector_icon:"🏪",total_projects:6, avg_physical_pct:57,financial_utilisation_pct:51,delayed_count:1,dc_flag_count:1,total_sanctioned_lakhs:28700},
  {sector_code:"BEAUTY",sector_name:"Beautification",  sector_icon:"🌳",total_projects:6, avg_physical_pct:91,financial_utilisation_pct:87,delayed_count:0,dc_flag_count:0,total_sanctioned_lakhs:11200},
  {sector_code:"ROAD",  sector_name:"Road & Bridges",  sector_icon:"🛣",total_projects:8, avg_physical_pct:47,financial_utilisation_pct:41,delayed_count:3,dc_flag_count:3,total_sanctioned_lakhs:84600},
];

const PROJECT_PHASES = ["Conceptualization","Pre-Tender","Tender","Post-Tender","Construction","O&M","Completed"];
const ACTIVE_TENDER_PHASES = ["Conceptualization","Pre-Tender","Tender","Post-Tender"];
// Role permissions: MD can edit+add, DC can view only, PMU_ENGINEER can edit only
const ROLE_PERMISSIONS = {
  MD:           { can_edit:true,  can_add:true  },
  DC:           { can_edit:false, can_add:false },
  PMU_ENGINEER: { can_edit:true,  can_add:false },
  FINANCE:      { can_edit:false, can_add:false },
  READ_ONLY:    { can_edit:false, can_add:false },
};

const DISTRICTS = [
  "Patna","Muzaffarpur","Gaya","Bhagalpur","Darbhanga","Begusarai",
  "Purnia","Ara","Samastipur","Munger","Chapra","Sitamarhi","Madhubani","Supaul","Saharsa"
];

let _nextId = 76;
const PROJECTS_INIT = [
  // WATER (8)
  {project_id:1, project_code:"BU/WATER/PAT/2021/07",project_name:"Patna 24×7 Water Supply",         sector_code:"WATER",sector_name:"Water Supply",   sector_icon:"💧",district:"Patna",      ulb_name:"Patna",      contractor_name:"L&T Construction",       current_sanctioned_cost:91000,financial_progress_pct:71.2,actual_physical_pct:74,scheduled_physical_pct:70,delay_days:0,  planned_end_date:"2026-09-30",revised_end_date:null,        total_cos_count:1,total_eot_days:0,  phase:"Construction",delay_reason:null,           dept_stuck:null,               latitude:25.5941,longitude:85.1376,chainage:null,         status:"IN_PROGRESS"},
  {project_id:2, project_code:"BU/WATER/GAY/2025/01",project_name:"Gaya Water Treatment Plant",       sector_code:"WATER",sector_name:"Water Supply",   sector_icon:"💧",district:"Gaya",       ulb_name:"Gaya",       contractor_name:"TBD",                     current_sanctioned_cost:31000,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2028-03-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Conceptualization",delay_reason:null,       dept_stuck:null,               latitude:24.8000,longitude:85.0100,chainage:null,         status:"DPR_STAGE"},
  {project_id:3, project_code:"BU/WATER/MUZ/2023/04",project_name:"Muzaffarpur Water Supply Aug.",    sector_code:"WATER",sector_name:"Water Supply",   sector_icon:"💧",district:"Muzaffarpur",ulb_name:"Muzaffarpur",contractor_name:"Dilip Buildcon Ltd",      current_sanctioned_cost:54200,financial_progress_pct:44.1,actual_physical_pct:47,scheduled_physical_pct:55,delay_days:18, planned_end_date:"2026-03-31",revised_end_date:"2026-06-30",total_cos_count:1,total_eot_days:31,  phase:"Construction",delay_reason:"Land acquisition pending",dept_stuck:"Revenue Dept",    latitude:26.1197,longitude:85.3910,chainage:null,         status:"IN_PROGRESS"},
  {project_id:4, project_code:"BU/WATER/BGS/2022/02",project_name:"Begusarai OHT & Dist. Network",    sector_code:"WATER",sector_name:"Water Supply",   sector_icon:"💧",district:"Begusarai",  ulb_name:"Begusarai",  contractor_name:"PNC Infratech",           current_sanctioned_cost:38700,financial_progress_pct:62.5,actual_physical_pct:65,scheduled_physical_pct:62,delay_days:0,  planned_end_date:"2026-12-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Construction",delay_reason:null,           dept_stuck:null,               latitude:25.4182,longitude:86.1272,chainage:null,         status:"IN_PROGRESS"},
  {project_id:5, project_code:"BU/WATER/DSB/2024/03",project_name:"Darbhanga Piped Water Project",    sector_code:"WATER",sector_name:"Water Supply",   sector_icon:"💧",district:"Darbhanga",  ulb_name:"Darbhanga",  contractor_name:"Tata Projects",           current_sanctioned_cost:42800,financial_progress_pct:18.2,actual_physical_pct:20,scheduled_physical_pct:25,delay_days:12, planned_end_date:"2027-06-30",revised_end_date:"2027-09-30",total_cos_count:0,total_eot_days:30,  phase:"Pre-Tender",  delay_reason:"Utility NOC pending",  dept_stuck:"BSPHCL",           latitude:26.1542,longitude:85.9000,chainage:null,         status:"IN_PROGRESS"},
  {project_id:6, project_code:"BU/WATER/BHG/2021/05",project_name:"Bhagalpur Water Supply Phase-I",   sector_code:"WATER",sector_name:"Water Supply",   sector_icon:"💧",district:"Bhagalpur",  ulb_name:"Bhagalpur",  contractor_name:"Afcons Infrastructure",   current_sanctioned_cost:68400,financial_progress_pct:85.3,actual_physical_pct:88,scheduled_physical_pct:85,delay_days:0,  planned_end_date:"2026-06-30",revised_end_date:null,        total_cos_count:2,total_eot_days:0,  phase:"O&M",         delay_reason:null,           dept_stuck:null,               latitude:25.2425,longitude:86.9842,chainage:null,         status:"IN_PROGRESS"},
  {project_id:7, project_code:"BU/WATER/PUR/2023/06",project_name:"Purnia Water Supply Aug.",          sector_code:"WATER",sector_name:"Water Supply",   sector_icon:"💧",district:"Purnia",     ulb_name:"Purnia",     contractor_name:"NCC Ltd",                 current_sanctioned_cost:29100,financial_progress_pct:31.4,actual_physical_pct:33,scheduled_physical_pct:40,delay_days:22, planned_end_date:"2026-09-30",revised_end_date:"2026-12-31",total_cos_count:1,total_eot_days:90,  phase:"Construction",delay_reason:"Contractor default",    dept_stuck:"PMU Purnia",       latitude:25.7771,longitude:87.4753,chainage:null,         status:"IN_PROGRESS"},
  {project_id:8, project_code:"BU/WATER/SMH/2024/07",project_name:"Sitamarhi Water Grid Phase-I",     sector_code:"WATER",sector_name:"Water Supply",   sector_icon:"💧",district:"Sitamarhi",  ulb_name:"Sitamarhi",  contractor_name:"TBD",                     current_sanctioned_cost:33500,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2028-12-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Tender",      delay_reason:null,           dept_stuck:null,               latitude:26.5940,longitude:85.4900,chainage:null,         status:"TENDERING"},
  // SEW (7)
  {project_id:9, project_code:"BU/SEW/MUZ/2022/03", project_name:"Muzaffarpur STP Phase-II",          sector_code:"SEW",  sector_name:"Sewerage & STP",sector_icon:"🏗",district:"Muzaffarpur",ulb_name:"Muzaffarpur",contractor_name:"M/s XYZ Infra Pvt Ltd",   current_sanctioned_cost:48200,financial_progress_pct:58.4,actual_physical_pct:52,scheduled_physical_pct:65,delay_days:47, planned_end_date:"2025-12-31",revised_end_date:"2026-03-31",total_cos_count:2,total_eot_days:90,  phase:"Construction",delay_reason:"Contractor demobilised",dept_stuck:"PMU Muzaffarpur",  latitude:26.1197,longitude:85.3910,chainage:null,         status:"STALLED"},
  {project_id:10,project_code:"BU/SEW/PAT/2025/02", project_name:"Patna Sewerage Trunk Main",          sector_code:"SEW",  sector_name:"Sewerage & STP",sector_icon:"🏗",district:"Patna",      ulb_name:"Patna",      contractor_name:"TBD",                     current_sanctioned_cost:74000,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2028-09-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Pre-Tender",  delay_reason:null,           dept_stuck:null,               latitude:25.6000,longitude:85.1200,chainage:null,         status:"DPR_STAGE"},
  {project_id:11,project_code:"BU/SEW/GAY/2022/04", project_name:"Gaya STP & Sewer Network",           sector_code:"SEW",  sector_name:"Sewerage & STP",sector_icon:"🏗",district:"Gaya",       ulb_name:"Gaya",       contractor_name:"Shapoorji Pallonji",       current_sanctioned_cost:56400,financial_progress_pct:49.2,actual_physical_pct:43,scheduled_physical_pct:60,delay_days:31, planned_end_date:"2026-03-31",revised_end_date:"2026-06-30",total_cos_count:1,total_eot_days:60,  phase:"Construction",delay_reason:"Forest NOC pending",   dept_stuck:"Forest Dept",      latitude:24.7914,longitude:85.0002,chainage:null,         status:"IN_PROGRESS"},
  {project_id:12,project_code:"BU/SEW/BHG/2023/05", project_name:"Bhagalpur UGD Interceptor Sewer",    sector_code:"SEW",  sector_name:"Sewerage & STP",sector_icon:"🏗",district:"Bhagalpur",  ulb_name:"Bhagalpur",  contractor_name:"Hindustan Construction",   current_sanctioned_cost:38900,financial_progress_pct:27.1,actual_physical_pct:25,scheduled_physical_pct:35,delay_days:18, planned_end_date:"2027-03-31",revised_end_date:"2027-06-30",total_cos_count:0,total_eot_days:90,  phase:"Construction",delay_reason:"EoT applied",          dept_stuck:null,               latitude:25.2425,longitude:86.9842,chainage:null,         status:"IN_PROGRESS"},
  {project_id:13,project_code:"BU/SEW/DSB/2024/06", project_name:"Darbhanga Sewerage Phase-I",          sector_code:"SEW",  sector_name:"Sewerage & STP",sector_icon:"🏗",district:"Darbhanga",  ulb_name:"Darbhanga",  contractor_name:"TBD",                     current_sanctioned_cost:45100,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2028-06-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Tender",      delay_reason:null,           dept_stuck:null,               latitude:26.1542,longitude:85.9000,chainage:null,         status:"TENDERING"},
  {project_id:14,project_code:"BU/SEW/BGS/2021/01", project_name:"Begusarai Sewerage & STP",            sector_code:"SEW",  sector_name:"Sewerage & STP",sector_icon:"🏗",district:"Begusarai",  ulb_name:"Begusarai",  contractor_name:"L&T ECC",                 current_sanctioned_cost:61200,financial_progress_pct:78.4,actual_physical_pct:81,scheduled_physical_pct:80,delay_days:0,  planned_end_date:"2026-06-30",revised_end_date:null,        total_cos_count:1,total_eot_days:0,  phase:"O&M",         delay_reason:null,           dept_stuck:null,               latitude:25.4182,longitude:86.1272,chainage:null,         status:"IN_PROGRESS"},
  {project_id:15,project_code:"BU/SEW/ARA/2023/07", project_name:"Ara Town Sewerage Network",            sector_code:"SEW",  sector_name:"Sewerage & STP",sector_icon:"🏗",district:"Ara",        ulb_name:"Ara",        contractor_name:"NCC Ltd",                 current_sanctioned_cost:28200,financial_progress_pct:35.6,actual_physical_pct:31,scheduled_physical_pct:45,delay_days:25, planned_end_date:"2026-09-30",revised_end_date:"2026-12-31",total_cos_count:0,total_eot_days:90,  phase:"Construction",delay_reason:"EoT pending",          dept_stuck:"PMU Ara",          latitude:25.5624,longitude:84.6651,chainage:null,         status:"IN_PROGRESS"},
  // DRAIN (7)
  {project_id:16,project_code:"BU/DRAIN/GAY/2023/01",project_name:"Gaya Storm Drain Network",           sector_code:"DRAIN",sector_name:"Storm Drainage",sector_icon:"🌧",district:"Gaya",       ulb_name:"Gaya",       contractor_name:"Dilip Buildcon Ltd",      current_sanctioned_cost:23400,financial_progress_pct:38.1,actual_physical_pct:35,scheduled_physical_pct:50,delay_days:22, planned_end_date:"2026-06-30",revised_end_date:"2026-07-31",total_cos_count:0,total_eot_days:31,  phase:"Construction",delay_reason:"BG expiry risk",       dept_stuck:"Finance Section",  latitude:24.7914,longitude:85.0002,chainage:null,         status:"IN_PROGRESS"},
  {project_id:17,project_code:"BU/DRAIN/PAT/2022/02",project_name:"Patna Central Drain Upgradation",    sector_code:"DRAIN",sector_name:"Storm Drainage",sector_icon:"🌧",district:"Patna",      ulb_name:"Patna",      contractor_name:"L&T Construction",        current_sanctioned_cost:38900,financial_progress_pct:65.4,actual_physical_pct:68,scheduled_physical_pct:65,delay_days:0,  planned_end_date:"2026-09-30",revised_end_date:null,        total_cos_count:1,total_eot_days:0,  phase:"Construction",delay_reason:null,           dept_stuck:null,               latitude:25.5941,longitude:85.1376,chainage:null,         status:"IN_PROGRESS"},
  {project_id:18,project_code:"BU/DRAIN/MUZ/2023/03",project_name:"Muzaffarpur Drainage Master Plan",   sector_code:"DRAIN",sector_name:"Storm Drainage",sector_icon:"🌧",district:"Muzaffarpur",ulb_name:"Muzaffarpur",contractor_name:"Afcons Infrastructure",   current_sanctioned_cost:29100,financial_progress_pct:42.1,actual_physical_pct:40,scheduled_physical_pct:55,delay_days:28, planned_end_date:"2026-03-31",revised_end_date:"2026-06-30",total_cos_count:1,total_eot_days:90,  phase:"Construction",delay_reason:"Design change",        dept_stuck:null,               latitude:26.1197,longitude:85.3910,chainage:null,         status:"IN_PROGRESS"},
  {project_id:19,project_code:"BU/DRAIN/BHG/2024/04",project_name:"Bhagalpur Stormwater Channel",       sector_code:"DRAIN",sector_name:"Storm Drainage",sector_icon:"🌧",district:"Bhagalpur",  ulb_name:"Bhagalpur",  contractor_name:"TBD",                     current_sanctioned_cost:19800,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2027-12-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Tender",      delay_reason:null,           dept_stuck:null,               latitude:25.2425,longitude:86.9842,chainage:null,         status:"TENDERING"},
  {project_id:20,project_code:"BU/DRAIN/DSB/2022/05",project_name:"Darbhanga Urban Flood Management",   sector_code:"DRAIN",sector_name:"Storm Drainage",sector_icon:"🌧",district:"Darbhanga",  ulb_name:"Darbhanga",  contractor_name:"Hindustan Construction",   current_sanctioned_cost:41200,financial_progress_pct:57.8,actual_physical_pct:61,scheduled_physical_pct:60,delay_days:0,  planned_end_date:"2026-12-31",revised_end_date:null,        total_cos_count:2,total_eot_days:0,  phase:"Construction",delay_reason:null,           dept_stuck:null,               latitude:26.1542,longitude:85.9000,chainage:null,         status:"IN_PROGRESS"},
  {project_id:21,project_code:"BU/DRAIN/BGS/2023/06",project_name:"Begusarai Drain Network Phase-I",    sector_code:"DRAIN",sector_name:"Storm Drainage",sector_icon:"🌧",district:"Begusarai",  ulb_name:"Begusarai",  contractor_name:"NCC Ltd",                 current_sanctioned_cost:21400,financial_progress_pct:29.6,actual_physical_pct:27,scheduled_physical_pct:35,delay_days:15, planned_end_date:"2026-09-30",revised_end_date:"2026-12-31",total_cos_count:0,total_eot_days:60,  phase:"Construction",delay_reason:"Funding delay",        dept_stuck:null,               latitude:25.4182,longitude:86.1272,chainage:null,         status:"IN_PROGRESS"},
  {project_id:22,project_code:"BU/DRAIN/PUR/2024/07",project_name:"Purnia Drain Rehabilitation",        sector_code:"DRAIN",sector_name:"Storm Drainage",sector_icon:"🌧",district:"Purnia",     ulb_name:"Purnia",     contractor_name:"TBD",                     current_sanctioned_cost:14200,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2028-06-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Conceptualization",delay_reason:null,       dept_stuck:null,               latitude:25.7771,longitude:87.4753,chainage:null,         status:"DPR_STAGE"},
  // SWM (6)
  {project_id:23,project_code:"BU/SWM/PAT/2022/01",  project_name:"Patna SWM Integrated System",        sector_code:"SWM",  sector_name:"Solid Waste",   sector_icon:"♻",district:"Patna",      ulb_name:"Patna",      contractor_name:"Ramky Enviro",            current_sanctioned_cost:52400,financial_progress_pct:73.1,actual_physical_pct:76,scheduled_physical_pct:74,delay_days:0,  planned_end_date:"2026-09-30",revised_end_date:null,        total_cos_count:1,total_eot_days:0,  phase:"Construction",delay_reason:null,           dept_stuck:null,               latitude:25.5941,longitude:85.1376,chainage:null,         status:"IN_PROGRESS"},
  {project_id:24,project_code:"BU/SWM/MUZ/2022/02",  project_name:"Muzaffarpur Waste Processing Plant",  sector_code:"SWM",  sector_name:"Solid Waste",   sector_icon:"♻",district:"Muzaffarpur",ulb_name:"Muzaffarpur",contractor_name:"IL&FS Environmental",     current_sanctioned_cost:38100,financial_progress_pct:68.4,actual_physical_pct:71,scheduled_physical_pct:70,delay_days:0,  planned_end_date:"2026-06-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"O&M",         delay_reason:null,           dept_stuck:null,               latitude:26.1197,longitude:85.3910,chainage:null,         status:"IN_PROGRESS"},
  {project_id:25,project_code:"BU/SWM/GAY/2023/03",  project_name:"Gaya SWM Collection & Transport",     sector_code:"SWM",  sector_name:"Solid Waste",   sector_icon:"♻",district:"Gaya",       ulb_name:"Gaya",       contractor_name:"Ecogreen Energy",         current_sanctioned_cost:24800,financial_progress_pct:82.1,actual_physical_pct:85,scheduled_physical_pct:84,delay_days:0,  planned_end_date:"2026-03-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"O&M",         delay_reason:null,           dept_stuck:null,               latitude:24.7914,longitude:85.0002,chainage:null,         status:"IN_PROGRESS"},
  {project_id:26,project_code:"BU/SWM/BHG/2023/04",  project_name:"Bhagalpur Urban Waste Management",    sector_code:"SWM",  sector_name:"Solid Waste",   sector_icon:"♻",district:"Bhagalpur",  ulb_name:"Bhagalpur",  contractor_name:"Antony Waste Handling",   current_sanctioned_cost:31200,financial_progress_pct:52.3,actual_physical_pct:55,scheduled_physical_pct:60,delay_days:12, planned_end_date:"2026-09-30",revised_end_date:"2026-12-31",total_cos_count:0,total_eot_days:60,  phase:"Construction",delay_reason:"Seasonal delay",       dept_stuck:null,               latitude:25.2425,longitude:86.9842,chainage:null,         status:"IN_PROGRESS"},
  {project_id:27,project_code:"BU/SWM/DSB/2024/05",  project_name:"Darbhanga Sanitation Improvement",    sector_code:"SWM",  sector_name:"Solid Waste",   sector_icon:"♻",district:"Darbhanga",  ulb_name:"Darbhanga",  contractor_name:"TBD",                     current_sanctioned_cost:18900,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2027-12-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Tender",      delay_reason:null,           dept_stuck:null,               latitude:26.1542,longitude:85.9000,chainage:null,         status:"TENDERING"},
  {project_id:28,project_code:"BU/SWM/BGS/2022/06",  project_name:"Begusarai SWM Project",               sector_code:"SWM",  sector_name:"Solid Waste",   sector_icon:"♻",district:"Begusarai",  ulb_name:"Begusarai",  contractor_name:"Ramky Enviro",            current_sanctioned_cost:27800,financial_progress_pct:61.4,actual_physical_pct:64,scheduled_physical_pct:65,delay_days:0,  planned_end_date:"2026-12-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Construction",delay_reason:null,           dept_stuck:null,               latitude:25.4182,longitude:86.1272,chainage:null,         status:"IN_PROGRESS"},
  // TRAN (7)
  {project_id:29,project_code:"BU/TRAN/BHG/2022/05", project_name:"Bhagalpur Bus Depot Complex",         sector_code:"TRAN", sector_name:"Urban Transport",sector_icon:"🚌",district:"Bhagalpur",  ulb_name:"Bhagalpur",  contractor_name:"PNC Infratech",           current_sanctioned_cost:36800,financial_progress_pct:22.3,actual_physical_pct:19,scheduled_physical_pct:40,delay_days:78, planned_end_date:"2025-09-30",revised_end_date:"2026-06-30",total_cos_count:3,total_eot_days:270, phase:"Construction",delay_reason:"3rd EoT — 270 days delay",dept_stuck:"PMU Bhagalpur", latitude:25.2425,longitude:86.9842,chainage:null,         status:"STALLED"},
  {project_id:30,project_code:"BU/TRAN/PAT/2021/01", project_name:"Patna Urban Transport Hub",           sector_code:"TRAN", sector_name:"Urban Transport",sector_icon:"🚌",district:"Patna",      ulb_name:"Patna",      contractor_name:"L&T Construction",        current_sanctioned_cost:84200,financial_progress_pct:44.1,actual_physical_pct:47,scheduled_physical_pct:55,delay_days:22, planned_end_date:"2026-06-30",revised_end_date:"2026-09-30",total_cos_count:1,total_eot_days:90,  phase:"Construction",delay_reason:"ROW clearance",        dept_stuck:"Revenue Dept",     latitude:25.5941,longitude:85.1376,chainage:null,         status:"IN_PROGRESS"},
  {project_id:31,project_code:"BU/TRAN/MUZ/2023/06", project_name:"Muzaffarpur BRTS Phase-I",            sector_code:"TRAN", sector_name:"Urban Transport",sector_icon:"🚌",district:"Muzaffarpur",ulb_name:"Muzaffarpur",contractor_name:"Afcons Infrastructure",   current_sanctioned_cost:52100,financial_progress_pct:12.4,actual_physical_pct:10,scheduled_physical_pct:30,delay_days:41, planned_end_date:"2026-12-31",revised_end_date:"2027-03-31",total_cos_count:1,total_eot_days:90,  phase:"Pre-Tender",  delay_reason:"Forest NOC pending",  dept_stuck:"Forest Department",latitude:26.1197,longitude:85.3910,chainage:null,         status:"IN_PROGRESS"},
  {project_id:32,project_code:"BU/TRAN/GAY/2024/07", project_name:"Gaya Multimodal Transit Centre",      sector_code:"TRAN", sector_name:"Urban Transport",sector_icon:"🚌",district:"Gaya",       ulb_name:"Gaya",       contractor_name:"TBD",                     current_sanctioned_cost:41800,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2028-06-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Tender",      delay_reason:null,           dept_stuck:null,               latitude:24.7914,longitude:85.0002,chainage:null,         status:"TENDERING"},
  {project_id:33,project_code:"BU/TRAN/DSB/2023/08", project_name:"Darbhanga Auto-Rickshaw Stand",       sector_code:"TRAN", sector_name:"Urban Transport",sector_icon:"🚌",district:"Darbhanga",  ulb_name:"Darbhanga",  contractor_name:"Hindustan Construction",   current_sanctioned_cost:18400,financial_progress_pct:62.4,actual_physical_pct:65,scheduled_physical_pct:64,delay_days:0,  planned_end_date:"2026-06-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"O&M",         delay_reason:null,           dept_stuck:null,               latitude:26.1542,longitude:85.9000,chainage:null,         status:"IN_PROGRESS"},
  {project_id:34,project_code:"BU/TRAN/BGS/2022/09", project_name:"Begusarai Truck Terminal",            sector_code:"TRAN", sector_name:"Urban Transport",sector_icon:"🚌",district:"Begusarai",  ulb_name:"Begusarai",  contractor_name:"NCC Ltd",                 current_sanctioned_cost:28900,financial_progress_pct:31.2,actual_physical_pct:28,scheduled_physical_pct:40,delay_days:31, planned_end_date:"2026-09-30",revised_end_date:"2026-12-31",total_cos_count:0,total_eot_days:60,  phase:"Construction",delay_reason:"Funding delay",        dept_stuck:null,               latitude:25.4182,longitude:86.1272,chainage:null,         status:"IN_PROGRESS"},
  {project_id:35,project_code:"BU/TRAN/PUR/2024/10", project_name:"Purnia City Bus Depot",               sector_code:"TRAN", sector_name:"Urban Transport",sector_icon:"🚌",district:"Purnia",     ulb_name:"Purnia",     contractor_name:"TBD",                     current_sanctioned_cost:22100,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2027-12-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Conceptualization",delay_reason:null,       dept_stuck:null,               latitude:25.7771,longitude:87.4753,chainage:null,         status:"DPR_STAGE"},
  // HOUSE (8)
  {project_id:36,project_code:"BU/HOUSE/PAT/2021/01",project_name:"Patna PMAY Urban Housing Phase-II",  sector_code:"HOUSE",sector_name:"Housing",       sector_icon:"🏘",district:"Patna",      ulb_name:"Patna",      contractor_name:"Shapoorji Pallonji",       current_sanctioned_cost:184200,financial_progress_pct:71.2,actual_physical_pct:74,scheduled_physical_pct:72,delay_days:0,  planned_end_date:"2026-09-30",revised_end_date:null,        total_cos_count:2,total_eot_days:0,  phase:"Construction",delay_reason:null,           dept_stuck:null,               latitude:25.5941,longitude:85.1376,chainage:null,         status:"IN_PROGRESS"},
  {project_id:37,project_code:"BU/HOUSE/MUZ/2022/02",project_name:"Muzaffarpur EWS Housing Colony",     sector_code:"HOUSE",sector_name:"Housing",       sector_icon:"🏘",district:"Muzaffarpur",ulb_name:"Muzaffarpur",contractor_name:"L&T Realty",              current_sanctioned_cost:94100,financial_progress_pct:63.4,actual_physical_pct:67,scheduled_physical_pct:65,delay_days:0,  planned_end_date:"2026-12-31",revised_end_date:null,        total_cos_count:1,total_eot_days:0,  phase:"Construction",delay_reason:null,           dept_stuck:null,               latitude:26.1197,longitude:85.3910,chainage:null,         status:"IN_PROGRESS"},
  {project_id:38,project_code:"BU/HOUSE/GAY/2022/03",project_name:"Gaya Affordable Housing Scheme",     sector_code:"HOUSE",sector_name:"Housing",       sector_icon:"🏘",district:"Gaya",       ulb_name:"Gaya",       contractor_name:"Prestige Group",          current_sanctioned_cost:72400,financial_progress_pct:58.1,actual_physical_pct:60,scheduled_physical_pct:62,delay_days:14, planned_end_date:"2026-06-30",revised_end_date:"2026-09-30",total_cos_count:0,total_eot_days:60,  phase:"Construction",delay_reason:"Design revision",      dept_stuck:null,               latitude:24.7914,longitude:85.0002,chainage:null,         status:"IN_PROGRESS"},
  {project_id:39,project_code:"BU/HOUSE/BHG/2023/04",project_name:"Bhagalpur LIG Housing Complex",     sector_code:"HOUSE",sector_name:"Housing",       sector_icon:"🏘",district:"Bhagalpur",  ulb_name:"Bhagalpur",  contractor_name:"NCC Ltd",                 current_sanctioned_cost:58700,financial_progress_pct:44.6,actual_physical_pct:48,scheduled_physical_pct:50,delay_days:8,  planned_end_date:"2026-09-30",revised_end_date:"2026-12-31",total_cos_count:0,total_eot_days:30,  phase:"Construction",delay_reason:"Minor EoT applied",    dept_stuck:null,               latitude:25.2425,longitude:86.9842,chainage:null,         status:"IN_PROGRESS"},
  {project_id:40,project_code:"BU/HOUSE/DSB/2023/05",project_name:"Darbhanga Urban Housing Project",   sector_code:"HOUSE",sector_name:"Housing",       sector_icon:"🏘",district:"Darbhanga",  ulb_name:"Darbhanga",  contractor_name:"Hindustan Construction",   current_sanctioned_cost:64800,financial_progress_pct:52.3,actual_physical_pct:55,scheduled_physical_pct:54,delay_days:0,  planned_end_date:"2027-03-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Construction",delay_reason:null,           dept_stuck:null,               latitude:26.1542,longitude:85.9000,chainage:null,         status:"IN_PROGRESS"},
  {project_id:41,project_code:"BU/HOUSE/BGS/2022/06",project_name:"Begusarai MIG Housing Scheme",      sector_code:"HOUSE",sector_name:"Housing",       sector_icon:"🏘",district:"Begusarai",  ulb_name:"Begusarai",  contractor_name:"Tata Housing",            current_sanctioned_cost:48200,financial_progress_pct:76.4,actual_physical_pct:79,scheduled_physical_pct:78,delay_days:0,  planned_end_date:"2026-06-30",revised_end_date:null,        total_cos_count:1,total_eot_days:0,  phase:"O&M",         delay_reason:null,           dept_stuck:null,               latitude:25.4182,longitude:86.1272,chainage:null,         status:"IN_PROGRESS"},
  {project_id:42,project_code:"BU/HOUSE/PUR/2024/07",project_name:"Purnia Slum Rehabilitation Housing",sector_code:"HOUSE",sector_name:"Housing",       sector_icon:"🏘",district:"Purnia",     ulb_name:"Purnia",     contractor_name:"TBD",                     current_sanctioned_cost:42100,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2028-03-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Tender",      delay_reason:null,           dept_stuck:null,               latitude:25.7771,longitude:87.4753,chainage:null,         status:"TENDERING"},
  {project_id:43,project_code:"BU/HOUSE/SMH/2024/08",project_name:"Sitamarhi PMAY Housing Block A",    sector_code:"HOUSE",sector_name:"Housing",       sector_icon:"🏘",district:"Sitamarhi",  ulb_name:"Sitamarhi",  contractor_name:"TBD",                     current_sanctioned_cost:36800,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2028-06-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Conceptualization",delay_reason:null,       dept_stuck:null,               latitude:26.5940,longitude:85.4900,chainage:null,         status:"DPR_STAGE"},
  // RIVER (6)
  {project_id:44,project_code:"BU/RIVER/PAT/2021/01",project_name:"Patna Ganga Riverfront Phase-I",    sector_code:"RIVER",sector_name:"Riverfront",    sector_icon:"🌊",district:"Patna",      ulb_name:"Patna",      contractor_name:"Gammon India",            current_sanctioned_cost:182400,financial_progress_pct:18.4,actual_physical_pct:20,scheduled_physical_pct:35,delay_days:62, planned_end_date:"2025-12-31",revised_end_date:"2026-06-30",total_cos_count:2,total_eot_days:180, phase:"Construction",delay_reason:"Court stay order",    dept_stuck:"PMU Patna",        latitude:25.5941,longitude:85.1376,chainage:null,         status:"STALLED"},
  {project_id:45,project_code:"BU/RIVER/BHG/2022/02",project_name:"Bhagalpur Ganga Ghats Development", sector_code:"RIVER",sector_name:"Riverfront",    sector_icon:"🌊",district:"Bhagalpur",  ulb_name:"Bhagalpur",  contractor_name:"Afcons Infrastructure",   current_sanctioned_cost:74200,financial_progress_pct:14.2,actual_physical_pct:12,scheduled_physical_pct:30,delay_days:45, planned_end_date:"2026-06-30",revised_end_date:"2026-09-30",total_cos_count:1,total_eot_days:90,  phase:"Construction",delay_reason:"ROW dispute",          dept_stuck:"Revenue Dept",     latitude:25.2425,longitude:86.9842,chainage:null,         status:"IN_PROGRESS"},
  {project_id:46,project_code:"BU/RIVER/MUZ/2023/03",project_name:"Muzaffarpur Burhi Gandak Riverfront",sector_code:"RIVER",sector_name:"Riverfront",   sector_icon:"🌊",district:"Muzaffarpur",ulb_name:"Muzaffarpur",contractor_name:"TBD",                     current_sanctioned_cost:38400,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2028-03-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Tender",      delay_reason:null,           dept_stuck:null,               latitude:26.1197,longitude:85.3910,chainage:null,         status:"TENDERING"},
  {project_id:47,project_code:"BU/RIVER/GAY/2023/04",project_name:"Gaya Falgu Riverfront Development", sector_code:"RIVER",sector_name:"Riverfront",    sector_icon:"🌊",district:"Gaya",       ulb_name:"Gaya",       contractor_name:"Shapoorji Pallonji",       current_sanctioned_cost:64200,financial_progress_pct:22.1,actual_physical_pct:20,scheduled_physical_pct:35,delay_days:38, planned_end_date:"2026-09-30",revised_end_date:"2026-12-31",total_cos_count:1,total_eot_days:90,  phase:"Construction",delay_reason:"Forest NOC",          dept_stuck:"Forest Dept",      latitude:24.7914,longitude:85.0002,chainage:null,         status:"IN_PROGRESS"},
  {project_id:48,project_code:"BU/RIVER/DSB/2024/05",project_name:"Darbhanga Bagmati Riverfront",      sector_code:"RIVER",sector_name:"Riverfront",    sector_icon:"🌊",district:"Darbhanga",  ulb_name:"Darbhanga",  contractor_name:"TBD",                     current_sanctioned_cost:44800,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2028-09-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Conceptualization",delay_reason:null,       dept_stuck:null,               latitude:26.1542,longitude:85.9000,chainage:null,         status:"DPR_STAGE"},
  {project_id:49,project_code:"BU/RIVER/BGS/2023/06",project_name:"Begusarai Burhi Gandak Riverfront", sector_code:"RIVER",sector_name:"Riverfront",    sector_icon:"🌊",district:"Begusarai",  ulb_name:"Begusarai",  contractor_name:"NCC Ltd",                 current_sanctioned_cost:56400,financial_progress_pct:12.8,actual_physical_pct:11,scheduled_physical_pct:25,delay_days:28, planned_end_date:"2026-12-31",revised_end_date:"2027-03-31",total_cos_count:0,total_eot_days:60,  phase:"Construction",delay_reason:"Land dispute",         dept_stuck:"Revenue Dept",     latitude:25.4182,longitude:86.1272,chainage:null,         status:"IN_PROGRESS"},
  // LIGHT (6)
  {project_id:50,project_code:"BU/LIGHT/DSB/2024/02",project_name:"Darbhanga LED Street Lighting",     sector_code:"LIGHT",sector_name:"Street Lighting",sector_icon:"💡",district:"Darbhanga",  ulb_name:"Darbhanga",  contractor_name:"Tata Projects",           current_sanctioned_cost:8900, financial_progress_pct:88.6,actual_physical_pct:92,scheduled_physical_pct:90,delay_days:0,  planned_end_date:"2026-06-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"O&M",         delay_reason:null,           dept_stuck:null,               latitude:26.1542,longitude:85.9000,chainage:null,         status:"IN_PROGRESS"},
  {project_id:51,project_code:"BU/LIGHT/PAT/2022/01",project_name:"Patna City LED Street Lighting",    sector_code:"LIGHT",sector_name:"Street Lighting",sector_icon:"💡",district:"Patna",      ulb_name:"Patna",      contractor_name:"Philips (Signify)",       current_sanctioned_cost:42100,financial_progress_pct:84.2,actual_physical_pct:87,scheduled_physical_pct:86,delay_days:0,  planned_end_date:"2026-03-31",revised_end_date:null,        total_cos_count:1,total_eot_days:0,  phase:"O&M",         delay_reason:null,           dept_stuck:null,               latitude:25.5941,longitude:85.1376,chainage:null,         status:"IN_PROGRESS"},
  {project_id:52,project_code:"BU/LIGHT/MUZ/2023/03",project_name:"Muzaffarpur LED Lighting Phase-I",  sector_code:"LIGHT",sector_name:"Street Lighting",sector_icon:"💡",district:"Muzaffarpur",ulb_name:"Muzaffarpur",contractor_name:"Tata Projects",           current_sanctioned_cost:18400,financial_progress_pct:78.4,actual_physical_pct:81,scheduled_physical_pct:80,delay_days:0,  planned_end_date:"2026-06-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"O&M",         delay_reason:null,           dept_stuck:null,               latitude:26.1197,longitude:85.3910,chainage:null,         status:"IN_PROGRESS"},
  {project_id:53,project_code:"BU/LIGHT/GAY/2023/04",project_name:"Gaya Heritage Zone Lighting",       sector_code:"LIGHT",sector_name:"Street Lighting",sector_icon:"💡",district:"Gaya",       ulb_name:"Gaya",       contractor_name:"IL&FS Engineering",       current_sanctioned_cost:14200,financial_progress_pct:72.1,actual_physical_pct:75,scheduled_physical_pct:74,delay_days:0,  planned_end_date:"2026-09-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"O&M",         delay_reason:null,           dept_stuck:null,               latitude:24.7914,longitude:85.0002,chainage:null,         status:"IN_PROGRESS"},
  {project_id:54,project_code:"BU/LIGHT/BHG/2024/05",project_name:"Bhagalpur Smart Street Lighting",   sector_code:"LIGHT",sector_name:"Street Lighting",sector_icon:"💡",district:"Bhagalpur",  ulb_name:"Bhagalpur",  contractor_name:"Havells India",           current_sanctioned_cost:22400,financial_progress_pct:38.1,actual_physical_pct:40,scheduled_physical_pct:45,delay_days:0,  planned_end_date:"2027-03-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Construction",delay_reason:null,           dept_stuck:null,               latitude:25.2425,longitude:86.9842,chainage:null,         status:"IN_PROGRESS"},
  {project_id:55,project_code:"BU/LIGHT/BGS/2024/06",project_name:"Begusarai LED Lighting Upgrade",    sector_code:"LIGHT",sector_name:"Street Lighting",sector_icon:"💡",district:"Begusarai",  ulb_name:"Begusarai",  contractor_name:"TBD",                     current_sanctioned_cost:12800,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2027-12-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Tender",      delay_reason:null,           dept_stuck:null,               latitude:25.4182,longitude:86.1272,chainage:null,         status:"TENDERING"},
  // MARKET (6)
  {project_id:56,project_code:"BU/MARKET/PAT/2022/01",project_name:"Patna Modern Vegetable Market",    sector_code:"MARKET",sector_name:"Markets",      sector_icon:"🏪",district:"Patna",      ulb_name:"Patna",      contractor_name:"Hindustan Construction",   current_sanctioned_cost:28400,financial_progress_pct:61.4,actual_physical_pct:65,scheduled_physical_pct:64,delay_days:0,  planned_end_date:"2026-06-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"O&M",         delay_reason:null,           dept_stuck:null,               latitude:25.5941,longitude:85.1376,chainage:null,         status:"IN_PROGRESS"},
  {project_id:57,project_code:"BU/MARKET/MUZ/2022/02",project_name:"Muzaffarpur Wholesale Market",     sector_code:"MARKET",sector_name:"Markets",      sector_icon:"🏪",district:"Muzaffarpur",ulb_name:"Muzaffarpur",contractor_name:"NCC Ltd",                 current_sanctioned_cost:38400,financial_progress_pct:52.3,actual_physical_pct:55,scheduled_physical_pct:58,delay_days:14, planned_end_date:"2026-09-30",revised_end_date:"2026-12-31",total_cos_count:1,total_eot_days:60,  phase:"Construction",delay_reason:"Utility shifting",    dept_stuck:"BSPHCL",           latitude:26.1197,longitude:85.3910,chainage:null,         status:"IN_PROGRESS"},
  {project_id:58,project_code:"BU/MARKET/GAY/2023/03",project_name:"Gaya Heritage Craft Market",       sector_code:"MARKET",sector_name:"Markets",      sector_icon:"🏪",district:"Gaya",       ulb_name:"Gaya",       contractor_name:"Prestige Contracts",      current_sanctioned_cost:18900,financial_progress_pct:44.1,actual_physical_pct:47,scheduled_physical_pct:48,delay_days:0,  planned_end_date:"2026-12-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Construction",delay_reason:null,           dept_stuck:null,               latitude:24.7914,longitude:85.0002,chainage:null,         status:"IN_PROGRESS"},
  {project_id:59,project_code:"BU/MARKET/BHG/2023/04",project_name:"Bhagalpur Silk Market Complex",    sector_code:"MARKET",sector_name:"Markets",      sector_icon:"🏪",district:"Bhagalpur",  ulb_name:"Bhagalpur",  contractor_name:"Afcons Infrastructure",   current_sanctioned_cost:42800,financial_progress_pct:38.6,actual_physical_pct:40,scheduled_physical_pct:50,delay_days:21, planned_end_date:"2026-09-30",revised_end_date:"2026-12-31",total_cos_count:0,total_eot_days:90,  phase:"Construction",delay_reason:"EoT pending",          dept_stuck:null,               latitude:25.2425,longitude:86.9842,chainage:null,         status:"IN_PROGRESS"},
  {project_id:60,project_code:"BU/MARKET/DSB/2024/05",project_name:"Darbhanga Weekly Market Upgrade",  sector_code:"MARKET",sector_name:"Markets",      sector_icon:"🏪",district:"Darbhanga",  ulb_name:"Darbhanga",  contractor_name:"TBD",                     current_sanctioned_cost:12400,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2027-12-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Tender",      delay_reason:null,           dept_stuck:null,               latitude:26.1542,longitude:85.9000,chainage:null,         status:"TENDERING"},
  {project_id:61,project_code:"BU/MARKET/BGS/2023/06",project_name:"Begusarai APMC Market",            sector_code:"MARKET",sector_name:"Markets",      sector_icon:"🏪",district:"Begusarai",  ulb_name:"Begusarai",  contractor_name:"IL&FS Engineering",       current_sanctioned_cost:21200,financial_progress_pct:55.2,actual_physical_pct:58,scheduled_physical_pct:57,delay_days:0,  planned_end_date:"2026-06-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Construction",delay_reason:null,           dept_stuck:null,               latitude:25.4182,longitude:86.1272,chainage:null,         status:"IN_PROGRESS"},
  // BEAUTY (6)
  {project_id:62,project_code:"BU/BEAUTY/PAT/2021/01",project_name:"Patna City Park & Promenade",      sector_code:"BEAUTY",sector_name:"Beautification",sector_icon:"🌳",district:"Patna",     ulb_name:"Patna",      contractor_name:"Tata Projects",           current_sanctioned_cost:24100,financial_progress_pct:91.2,actual_physical_pct:94,scheduled_physical_pct:92,delay_days:0,  planned_end_date:"2026-06-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"O&M",         delay_reason:null,           dept_stuck:null,               latitude:25.5941,longitude:85.1376,chainage:null,         status:"IN_PROGRESS"},
  {project_id:63,project_code:"BU/BEAUTY/MUZ/2022/02",project_name:"Muzaffarpur Urban Greenery",       sector_code:"BEAUTY",sector_name:"Beautification",sector_icon:"🌳",district:"Muzaffarpur",ulb_name:"Muzaffarpur",contractor_name:"Shapoorji Pallonji",       current_sanctioned_cost:14800,financial_progress_pct:84.1,actual_physical_pct:87,scheduled_physical_pct:86,delay_days:0,  planned_end_date:"2026-03-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"O&M",         delay_reason:null,           dept_stuck:null,               latitude:26.1197,longitude:85.3910,chainage:null,         status:"IN_PROGRESS"},
  {project_id:64,project_code:"BU/BEAUTY/GAY/2022/03",project_name:"Gaya Heritage Zone Beautification",sector_code:"BEAUTY",sector_name:"Beautification",sector_icon:"🌳",district:"Gaya",      ulb_name:"Gaya",       contractor_name:"L&T Construction",        current_sanctioned_cost:18400,financial_progress_pct:88.4,actual_physical_pct:91,scheduled_physical_pct:90,delay_days:0,  planned_end_date:"2026-06-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"O&M",         delay_reason:null,           dept_stuck:null,               latitude:24.7914,longitude:85.0002,chainage:null,         status:"IN_PROGRESS"},
  {project_id:65,project_code:"BU/BEAUTY/BHG/2023/04",project_name:"Bhagalpur Waterfront Beautification",sector_code:"BEAUTY",sector_name:"Beautification",sector_icon:"🌳",district:"Bhagalpur",ulb_name:"Bhagalpur",contractor_name:"NCC Ltd",                current_sanctioned_cost:12200,financial_progress_pct:72.1,actual_physical_pct:75,scheduled_physical_pct:74,delay_days:0,  planned_end_date:"2026-09-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Construction",delay_reason:null,           dept_stuck:null,               latitude:25.2425,longitude:86.9842,chainage:null,         status:"IN_PROGRESS"},
  {project_id:66,project_code:"BU/BEAUTY/DSB/2024/05",project_name:"Darbhanga Urban Landscape",         sector_code:"BEAUTY",sector_name:"Beautification",sector_icon:"🌳",district:"Darbhanga",  ulb_name:"Darbhanga",  contractor_name:"TBD",                     current_sanctioned_cost:9400, financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2027-12-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Tender",      delay_reason:null,           dept_stuck:null,               latitude:26.1542,longitude:85.9000,chainage:null,         status:"TENDERING"},
  {project_id:67,project_code:"BU/BEAUTY/BGS/2023/06",project_name:"Begusarai City Centre Beautification",sector_code:"BEAUTY",sector_name:"Beautification",sector_icon:"🌳",district:"Begusarai",ulb_name:"Begusarai",contractor_name:"Prestige Contracts",      current_sanctioned_cost:13200,financial_progress_pct:81.4,actual_physical_pct:84,scheduled_physical_pct:83,delay_days:0,  planned_end_date:"2026-06-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"O&M",         delay_reason:null,           dept_stuck:null,               latitude:25.4182,longitude:86.1272,chainage:null,         status:"IN_PROGRESS"},
  // ROAD (8)
  {project_id:68,project_code:"BU/ROAD/MUZ/2024/01", project_name:"Muzaffarpur Ring Road Upgradation",  sector_code:"ROAD", sector_name:"Road & Bridges",sector_icon:"🛣",district:"Muzaffarpur",ulb_name:"Muzaffarpur",contractor_name:"Afcons Infrastructure",   current_sanctioned_cost:52000,financial_progress_pct:12.0,actual_physical_pct:8, scheduled_physical_pct:30,delay_days:35, planned_end_date:"2026-12-31",revised_end_date:"2027-03-31",total_cos_count:1,total_eot_days:90,  phase:"Pre-Tender",  delay_reason:"Forest NOC pending",  dept_stuck:"Forest Department",latitude:26.1300,longitude:85.4100,chainage:"Km 0+000 to Km 18+500",status:"IN_PROGRESS"},
  {project_id:69,project_code:"BU/ROAD/PAT/2022/02",  project_name:"Patna ROB & Approach Roads",         sector_code:"ROAD", sector_name:"Road & Bridges",sector_icon:"🛣",district:"Patna",      ulb_name:"Patna",      contractor_name:"L&T Construction",        current_sanctioned_cost:142400,financial_progress_pct:58.4,actual_physical_pct:62,scheduled_physical_pct:60,delay_days:0,  planned_end_date:"2026-09-30",revised_end_date:null,        total_cos_count:2,total_eot_days:0,  phase:"Construction",delay_reason:null,           dept_stuck:null,               latitude:25.5941,longitude:85.1376,chainage:"Km 0+000 to Km 6+200",status:"IN_PROGRESS"},
  {project_id:70,project_code:"BU/ROAD/GAY/2023/03",  project_name:"Gaya Ring Road Phase-I",             sector_code:"ROAD", sector_name:"Road & Bridges",sector_icon:"🛣",district:"Gaya",       ulb_name:"Gaya",       contractor_name:"Dilip Buildcon Ltd",      current_sanctioned_cost:84200,financial_progress_pct:38.6,actual_physical_pct:41,scheduled_physical_pct:55,delay_days:28, planned_end_date:"2026-03-31",revised_end_date:"2026-06-30",total_cos_count:1,total_eot_days:90,  phase:"Construction",delay_reason:"Utility shifting",    dept_stuck:"BSPHCL",           latitude:24.7914,longitude:85.0002,chainage:"Km 0+000 to Km 22+400",status:"IN_PROGRESS"},
  {project_id:71,project_code:"BU/ROAD/BHG/2022/04",  project_name:"Bhagalpur City Road Network",        sector_code:"ROAD", sector_name:"Road & Bridges",sector_icon:"🛣",district:"Bhagalpur",  ulb_name:"Bhagalpur",  contractor_name:"PNC Infratech",           current_sanctioned_cost:62100,financial_progress_pct:72.1,actual_physical_pct:75,scheduled_physical_pct:73,delay_days:0,  planned_end_date:"2026-06-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Construction",delay_reason:null,           dept_stuck:null,               latitude:25.2425,longitude:86.9842,chainage:"Km 0+000 to Km 14+100",status:"IN_PROGRESS"},
  {project_id:72,project_code:"BU/ROAD/DSB/2023/05",  project_name:"Darbhanga Bypass Road",              sector_code:"ROAD", sector_name:"Road & Bridges",sector_icon:"🛣",district:"Darbhanga",  ulb_name:"Darbhanga",  contractor_name:"NCC Ltd",                 current_sanctioned_cost:78400,financial_progress_pct:31.4,actual_physical_pct:29,scheduled_physical_pct:45,delay_days:42, planned_end_date:"2026-09-30",revised_end_date:"2026-12-31",total_cos_count:1,total_eot_days:90,  phase:"Construction",delay_reason:"Land acquisition",    dept_stuck:"Revenue Dept",     latitude:26.1542,longitude:85.9000,chainage:"Km 0+000 to Km 28+600",status:"IN_PROGRESS"},
  {project_id:73,project_code:"BU/ROAD/BGS/2023/06",  project_name:"Begusarai Industrial Road Link",     sector_code:"ROAD", sector_name:"Road & Bridges",sector_icon:"🛣",district:"Begusarai",  ulb_name:"Begusarai",  contractor_name:"Hindustan Construction",   current_sanctioned_cost:48200,financial_progress_pct:44.2,actual_physical_pct:47,scheduled_physical_pct:50,delay_days:14, planned_end_date:"2026-12-31",revised_end_date:"2027-03-31",total_cos_count:0,total_eot_days:60,  phase:"Construction",delay_reason:"ROW pending",          dept_stuck:"Revenue Dept",     latitude:25.4182,longitude:86.1272,chainage:"Km 0+000 to Km 11+800",status:"IN_PROGRESS"},
  {project_id:74,project_code:"BU/ROAD/PUR/2024/07",  project_name:"Purnia City Roads Improvement",      sector_code:"ROAD", sector_name:"Road & Bridges",sector_icon:"🛣",district:"Purnia",     ulb_name:"Purnia",     contractor_name:"TBD",                     current_sanctioned_cost:28400,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2028-03-31",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Tender",      delay_reason:null,           dept_stuck:null,               latitude:25.7771,longitude:87.4753,chainage:null,         status:"TENDERING"},
  {project_id:75,project_code:"BU/ROAD/SMH/2024/08",  project_name:"Sitamarhi Road Connectivity",        sector_code:"ROAD", sector_name:"Road & Bridges",sector_icon:"🛣",district:"Sitamarhi",  ulb_name:"Sitamarhi",  contractor_name:"TBD",                     current_sanctioned_cost:24200,financial_progress_pct:0,    actual_physical_pct:0, scheduled_physical_pct:0, delay_days:0,  planned_end_date:"2028-06-30",revised_end_date:null,        total_cos_count:0,total_eot_days:0,  phase:"Conceptualization",delay_reason:null,       dept_stuck:null,               latitude:26.5940,longitude:85.4900,chainage:null,         status:"DPR_STAGE"},
];

const COS_EOT_DATA = [
  {project_id:9, project_code:"BU/SEW/MUZ/2022/03", cos_number:"CoS-01",cos_date:"2023-08-15",cos_category:"SCOPE ADDITION",  cos_amount:320,cos_pct_variation:7.1,is_time_linked:true, eot_number:"EoT-01",eot_days_granted:60, original_end_date:"2025-12-31",new_end_date:"2026-02-28"},
  {project_id:9, project_code:"BU/SEW/MUZ/2022/03", cos_number:"CoS-02",cos_date:"2024-03-22",cos_category:"DESIGN CHANGE",   cos_amount:180,cos_pct_variation:3.7,is_time_linked:true, eot_number:"EoT-02",eot_days_granted:30, original_end_date:"2026-02-28",new_end_date:"2026-03-31"},
  {project_id:29,project_code:"BU/TRAN/BHG/2022/05",cos_number:"CoS-01",cos_date:"2023-05-10",cos_category:"QTY VARIATION",   cos_amount:210,cos_pct_variation:6.1,is_time_linked:true, eot_number:"EoT-01",eot_days_granted:90, original_end_date:"2025-09-30",new_end_date:"2025-12-31"},
  {project_id:29,project_code:"BU/TRAN/BHG/2022/05",cos_number:"CoS-02",cos_date:"2023-12-01",cos_category:"FORCE MAJEURE",   cos_amount:95, cos_pct_variation:2.6,is_time_linked:true, eot_number:"EoT-02",eot_days_granted:90, original_end_date:"2025-12-31",new_end_date:"2026-03-31"},
  {project_id:29,project_code:"BU/TRAN/BHG/2022/05",cos_number:"CoS-03",cos_date:"2024-07-15",cos_category:"SCOPE ADDITION",  cos_amount:145,cos_pct_variation:4.1,is_time_linked:true, eot_number:"EoT-03",eot_days_granted:90, original_end_date:"2026-03-31",new_end_date:"2026-06-30"},
  {project_id:68,project_code:"BU/ROAD/MUZ/2024/01",cos_number:"CoS-01",cos_date:"2025-01-10",cos_category:"SCOPE ADDITION",  cos_amount:420,cos_pct_variation:8.1,is_time_linked:true, eot_number:"EoT-01",eot_days_granted:90, original_end_date:"2026-12-31",new_end_date:"2027-03-31"},
  {project_id:44,project_code:"BU/RIVER/PAT/2021/01",cos_number:"CoS-01",cos_date:"2023-11-20",cos_category:"SCOPE ADDITION",  cos_amount:480,cos_pct_variation:9.2,is_time_linked:true, eot_number:"EoT-01",eot_days_granted:90, original_end_date:"2025-06-30",new_end_date:"2025-09-30"},
  {project_id:44,project_code:"BU/RIVER/PAT/2021/01",cos_number:"CoS-02",cos_date:"2024-06-15",cos_category:"COURT ORDER",    cos_amount:0,  cos_pct_variation:0,  is_time_linked:true, eot_number:"EoT-02",eot_days_granted:90, original_end_date:"2025-09-30",new_end_date:"2025-12-31"},
];

const projVariation = {};
COS_EOT_DATA.forEach(d=>{ if(!projVariation[d.project_id]) projVariation[d.project_id]=0; projVariation[d.project_id]+=d.cos_amount; });

const MANAGEMENT_FLAGS = [
  {flag_id:1,severity:"CRITICAL",days_open:47,flag_category:"Contractor Default",    flag_description:"Contractor demobilised — no activity on site for 47 days",                     action_required:"Issue NCN immediately. Explore invocation of PBG.",              responsible_dept:"PMU Muzaffarpur",   project_code:"BU/SEW/MUZ/2022/03",  project_name:"Muzaffarpur STP Phase-II",       sector_name:"Sewerage & STP", ulb_name:"Muzaffarpur",is_pre_monsoon:false},
  {flag_id:2,severity:"HIGH",    days_open:31,flag_category:"NOC Delay",            flag_description:"Forest NOC pending with Bihar Forest Dept — blocking 3.2km pipeline",            action_required:"Write to PCCF immediately. Escalate to MD for follow-up.",       responsible_dept:"Forest Department", project_code:"BU/WATER/PAT/2021/07", project_name:"Patna 24×7 Water Supply",        sector_name:"Water Supply",   ulb_name:"Patna",      is_pre_monsoon:false},
  {flag_id:3,severity:"HIGH",    days_open:78,flag_category:"EoT Overdue",          flag_description:"3rd EoT sought by contractor — total delay now 270 days",                        action_required:"Review EoT justification. MD approval required for >180 days.",  responsible_dept:"PMU Bhagalpur",     project_code:"BU/TRAN/BHG/2022/05", project_name:"Bhagalpur Bus Depot Complex",     sector_name:"Urban Transport",ulb_name:"Bhagalpur",  is_pre_monsoon:false},
  {flag_id:4,severity:"MEDIUM",  days_open:18,flag_category:"BG Expiry",            flag_description:"PBG worth ₹92 Lakhs expiring in 12 days — contractor not renewing",               action_required:"Issue 7-day notice. Prepare for encashment if no renewal.",      responsible_dept:"Finance Section",   project_code:"BU/DRAIN/GAY/2023/01", project_name:"Gaya Storm Drain Network",        sector_name:"Storm Drainage", ulb_name:"Gaya",       is_pre_monsoon:false},
  {flag_id:5,severity:"CRITICAL",days_open:5, flag_category:"Pre-Monsoon Risk",     flag_description:"Open drain excavation across 4.2 km — heavy rain forecast, flood risk",          action_required:"Immediate backfilling or shoring. Emergency contractor meeting.", responsible_dept:"PMU Gaya",          project_code:"BU/DRAIN/GAY/2023/01", project_name:"Gaya Storm Drain Network",        sector_name:"Storm Drainage", ulb_name:"Gaya",       is_pre_monsoon:true},
  {flag_id:6,severity:"HIGH",    days_open:8, flag_category:"Pre-Monsoon Risk",     flag_description:"STP earthwork exposed — monsoon may cause slope failure",                         action_required:"Deploy waterproofing cover. Inspect slope stability.",           responsible_dept:"PMU Muzaffarpur",   project_code:"BU/SEW/MUZ/2022/03",  project_name:"Muzaffarpur STP Phase-II",       sector_name:"Sewerage & STP", ulb_name:"Muzaffarpur",is_pre_monsoon:true},
  {flag_id:7,severity:"HIGH",    days_open:3, flag_category:"Pre-Monsoon Risk",     flag_description:"Ring road cutting unstabilised — 650m stretch vulnerable to erosion",             action_required:"Deploy stone pitching / retaining walls before June 15.",        responsible_dept:"PMU Muzaffarpur",   project_code:"BU/ROAD/MUZ/2024/01", project_name:"Muzaffarpur Ring Road Upgradation",sector_name:"Road & Bridges", ulb_name:"Muzaffarpur",is_pre_monsoon:true},
  {flag_id:8,severity:"CRITICAL",days_open:62,flag_category:"Progress Stalled",     flag_description:"Ganga Riverfront — zero physical progress for 60+ days. Court stay.",            action_required:"Legal team review. Explore DPR modification to bypass stay.",    responsible_dept:"PMU Patna",         project_code:"BU/RIVER/PAT/2021/01", project_name:"Patna Ganga Riverfront Phase-I",  sector_name:"Riverfront",     ulb_name:"Patna",      is_pre_monsoon:false},
];